apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "patchworks-operator.fullname" . }}-manager-role
  labels:
  {{- include "patchworks-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches/finalizers
  verbs:
  - update
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "patchworks-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "patchworks-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "patchworks-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "patchworks-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
