apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "patchworks-operator.fullname" . }}-patch-viewer-role
  labels:
  {{- include "patchworks-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches/status
  verbs:
  - get
