apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "patchworks-operator.fullname" . }}-patch-editor-role
  labels:
  {{- include "patchworks-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches/status
  verbs:
  - get
