# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/joshbrgs/patchworks/internal/version.Version={{.Major}}.{{.Minor}}.{{.Patch}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"
