apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-controller-role
rules:
  - apiGroups: ["*"]  # Allow patching any resource
    resources: ["*"]
    verbs: ["get", "list", "watch", "patch", "update"]

