# permissions for end users to view patches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: patchworks
    app.kubernetes.io/managed-by: kustomize
  name: patch-viewer-role
rules:
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - patches.bigideaslearning.com
  resources:
  - patches/status
  verbs:
  - get
