---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - patches.joshb.io
  resources:
  - patches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - patches.joshb.io
  resources:
  - patches/finalizers
  verbs:
  - update
- apiGroups:
  - patches.joshb.io
  resources:
  - patches/status
  verbs:
  - get
  - patch
  - update
