apiVersion: patches.bigideaslearning.com/v1
kind: Patch
metadata:
  labels:
    app.kubernetes.io/name: patchworks
    app.kubernetes.io/managed-by: kustomize
  name: patch-sample
spec:
  target:
    kind: Deployment
    apiVersion: apps/v1
    name: nginx
    namespace: default
  source:
    kind: ConfigMap
    name: sample-config
  template: |
    spec:
      template:
        spec:
          containers:
            - name: nginx
              env:
                - name: APP_NAME_SINCE_IT
                  value: "{{ .name }}"
